### ISSUE TITLE
Health boost effect is unusable when provided by nourish

### ISSUE THREAD

**Issue by varencilator** [emilyploszaj/nourish#10]
Health boost keeps reapplying the health boost effect causing the player to take damage and reset their health to 10/12 hearts (10 is old max, 12 is new max health) while the conditions are true

**Comment by emilyploszaj** [comment]
I looked into it and it's a very weird case of how minecraft applies this effect, in version 1.3.2 you can provide entity attributes to change a player's max health instead of relying on health boost
