### ISSUE TITLE
Can't seem to get nourish datapack to work on server?

### ISSUE THREAD

**Issue by varencilator** [emilyploszaj/nourish#11]
It works completely fine when trying in a separate single player world but I can't get it to work on a server. I've tried it as folders an as a .zip but it keeps saying minecraft can't read the pack mcmeta.

"Couldn't find pack meta for pack file/Nourish"
"Couldn't get pack info for: net.minecraft.class_3266: 'pack.mcmeta' in ResourcePack '.\world\datapacks\Nourish.zip'"

**Comment by emilyploszaj** [comment]
Sorry I'm not sure what you're trying to do. Nourish is primarily controlled by a config that needs to be client/server synced and I'm not sure what you're using a datapack for other than tags, and if that is what it's about then it's pretty clear by the log that you're missing the mcmeta file.

**Comment by varencilator** [comment]
Sorry I'm dumb, not sure what I did wrong (maybe had Nourish instead of nourish in the datapack folder?) but I got it to work
