### ISSUE TITLE
[Suggestion] Compatibility options for Origins

### ISSUE THREAD

**Issue by copperwarrior** [emilyploszaj/nourish#13]
As the mod is right now, players with origins that don't allow them to eat specific types of foods still have nourish groups that they can't fulfill. I don't have any specific solution in mind, but some kind of option to assist this would be helpful.

**Comment by emilyploszaj** [comment]
Nourish has recently introduced nutrient profiles, and mods such as Origins have the ability to make their own nutrient profiles and apply them when individuals have origins
