### ISSUE TITLE
/nourish set is available without op

### ISSUE THREAD

**Issue by macbrayne** [emilyploszaj/nourish#5]
## How to reproduce

1. Setup a survival / hardcore world
2. Enter /nourish set carbohydrates 1
3. The command executes successfully

## Expected behaviour

/nourish get should work
/nourish set shouldn't work

**Comment by emilyploszaj** [comment]
This has been fixed in v1.2.1, I removed both `/nourish get` and `/nourish set` from survival, as they exist for creative shenanigans and debugging, and getting a precise internal value feels out of place in survival, thank you for your report.
